### ISSUE TITLE
Weighted Ejector duplicates items

### ISSUE THREAD

**Issue by Satex007** [datadever/IncrementalIndustries#2]
Using Version 0.0.3

Using the weighted ejector from Create somehow duplicates or even quadruples items.

I went from 1 analog circuit to over 4 stacks.

Later tested it with 1 gold ingot and the more you bounce the more you end up with.

**Comment by datadever** [comment]
bug reported to Create-Fabric team

**Comment by datadever** [comment]
will be fixed in next release along with new create version
