### ISSUE TITLE
Dirty mob slaughtering drill can't be washed

### ISSUE THREAD

**Issue by SilencedGoose** [datadever/IncrementalIndustries#4]
There seems to be no recipe for washing the mob slaughtering drill, just an empty box as the "output" in the recipe.
![image](https://user-images.githubusercontent.com/33594615/182398833-7fb659b4-eaeb-42d0-9d68-c0ec4eef207b.png)

The same looks to be the same with the andesite alloy drill.

**Comment by datadever** [comment]
Will be fixed in next update
